services:
  - type: web
    name: cybersecurity-platform
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('test', 'test@gmail.com', 'test123456789')"
    startCommand: gunicorn CyberSecurity_Platform.wsgi:application
